export const ERROR_CODE = {
    INVALID_DATA: 'INVALID_DATA',
    INVALID_USER_NAME: 'INVALID_USER',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR'
}

export const SUCCESS_CODE = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS'
}